refactor: OS check before running nested script

diff --git a/zkp-demo-test b/zkp-demo-test
--- a/zkp-demo-test
+++ b/zkp-demo-test
@@ -5,6 +5,15 @@ GREEN='\033[0;32m'
 RED='\033[0;31m'
 NC='\033[0m'
 
+systemInfo="$(uname -s)"
+case "${systemInfo}" in
+    Linux*)     machine=Linux;;
+    Darwin*)    machine=Mac;;
+    CYGWIN*)    machine=Cygwin;;
+    MINGW*)     machine=MinGw;;
+    *)          machine="UNKNOWN:${systemInfo}"
+esac
+
 printf "${GREEN}*** Cleaning up all test containers ***${NC}\n"
 docker-compose -f docker-compose.test.yml down -v || true
 
@@ -27,25 +36,24 @@ docker-compose -f docker-compose.test.yml up -d
 
 dir="$(pwd)"
 
-(osascript -e "
-  tell application \"Terminal\"
-    set currentTab to do script \"cd $dir\"
-    delay 2
-    do script \"docker-compose -f docker-compose.test.yml logs -f\" in currentTab
-  end tell") &
+if [ "${machine}" == "Mac" ]; then
+	osascript -e "
+	  tell application \"Terminal\"
+	    set currentTab to do script \"cd $dir\"
+	    delay 2
+	    do script \"docker-compose -f docker-compose.test.yml logs -f\" in currentTab
+	  end tell"
+fi
 
 sleep 30
 
-(
-	# RUN test suits and remove test containers
-	printf "${GREEN}*** Run Integration test ***${NC}\n"
-	npm run test
-) || printf "${RED}*** Integration test failed ***${NC}\n"
+# RUN test suits and remove test containers
+printf "${GREEN}*** Run Integration test ***${NC}\n"
+npm run test || printf "${RED}*** Integration test failed ***${NC}\n"
 
-(
-	printf "${GREEN}*** Cleaning up all test containers ***${NC}\n"
-	docker-compose -f docker-compose.test.yml down -v || true
-) || (
-	printf "${GREEN}*** Remove test-net network if not removed ***${NC}\n"
-	docker network rm nightfall_test_net
-)
+
+printf "${GREEN}*** Cleaning up all test containers ***${NC}\n"
+docker-compose -f docker-compose.test.yml down -v || true
+
+printf "${GREEN}*** Remove test-net network if not removed ***${NC}\n"
+docker network rm nightfall_test_net
